modules/member/controllers/ApplicationsController.php
<?php

namespace app\modules\member\controllers;

use Yii;
use app\models\Applications;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ApplicationsController implements the CRUD actions for Applications model.
 */
class ApplicationsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Applications models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Applications::find()->where(['user_id'=>\Yii::$app->user->id]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Applications model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Applications model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $alreadyMember = Applications::find()
            ->where(['user_id'=>\Yii::$app->user->id, 'category'=>'Membership','status'=>'Complete'])
            ->limit(1)->one();
        $alreadyApplying = Applications::find()
            ->where(['user_id'=>\Yii::$app->user->id, 'category'=>'Membership'])
            ->andWhere(['not',['status'=>'Complete']])
            ->limit(1)->one();
        if($alreadyMember){
            Yii::$app->session->setFlash('error','You are already a member!');
            return $this->redirect(['index']);
        }
        if($alreadyApplying){
            Yii::$app->session->setFlash('error','You already have an application being processed!');
            return $this->redirect(['index']);
        }
        $model = new Applications();
        $user = \app\models\Users::findOne(\Yii::$app->user->id);

        if ($model->load(Yii::$app->request->post()) && $user->load(Yii::$app->request->post()) && $model->save() && $user->save(false) ) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'user' => $user,            
        ]);
    }

    /**
     * Updates an existing Applications model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $user = \app\models\Users::findOne(\Yii::$app->user->id);

        if ($model->load(Yii::$app->request->post()) && $user->load(Yii::$app->request->post()) && $model->save() && $user->save(false) ) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'user' => $user,            
        ]);
    }


    public function actionSubmitApplication($id)
    {
        $model = $this->findModel($id);
        $model->status = 'Pending Approval';
        $model->save();
        Yii::$app->session->setFlash('success','Application submitted successfully and is pending approval!');
        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Applications model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Applications model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Applications the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Applications::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/member/controllers/PaymentsController.php
<?php

namespace app\modules\member\controllers;

use Yii;
use app\models\Payments;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PaymentsController implements the CRUD actions for Payments model.
 */
class PaymentsController extends Controller
{

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Payments models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Payments::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Payments model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Payments model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Payments();
        $application = \app\models\Applications::findOne($id);

        $alreadyPaid = Payments::find()
        ->where(['application_id'=>$id])->limit(1)->one();
        if($alreadyPaid){
            Yii::$app->session->setFlash('error','You already made a payment that is pending approval!');
            return $this->redirect(['applications/view','id'=>$id]);
        }

        if ($model->load(Yii::$app->request->post()) ) {
            $model->receipt = UploadedFile::getInstance($model, 'receipt');
            if($model->receipt){
                $photoPath = time().$model->receipt->baseName . '.' . $model->receipt->extension;
                $model->file = $photoPath;
                $model->user_id = \Yii::$app->user->id;
                $model->application_id = $id;
                $model->receipt->saveAs(Yii::getAlias('@webroot') .'/receipts/' . $photoPath);
                if($model->save()){
                    $application->status = $model->status;
                    $application->save(false);
                    Yii::$app->session->setFlash('success','Payment submitted successfully and is pending approval!');
                    return $this->redirect(['applications/view','id'=>$id]);        
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
            'application' => $application,
        ]);
    }

    public function actionOlycash($id)
    {
        $application = \app\models\Applications::findOne($id);

        
        $alreadyPaid = Payments::find()
        ->where(['application_id'=>$id])->limit(1)->one();
        if($alreadyPaid){
            Yii::$app->session->setFlash('error','You already made a payment that is pending approval!');
            return $this->redirect(['applications/view','id'=>$id]);
        }

        return $this->render('olycash', [
            'application' => $application,
        ]);
    }

    public function actionConfirm($id){
        // Yii::$app->controller->enableCsrfValidation = false;
        $application = \app\models\Applications::findOne($id);
        
        $purchase_id = $_POST['purchase_id'];
        $message = $_POST['message'];
        $payment_type = $_POST['payment_type'];
        if($message == 'success'){
            try {
                $model = new Payments();
                $model->user_id = \Yii::$app->user->id;
                $model->application_id = $id;
                $model->reference_number = $purchase_id;
                $model->payment_type ='Olycash';
                $model->amount = $application->user->membership->fee;
                $model->name =$application->user->name;
                $model->phone_number = $application->user->primary_phone_number;
                $model->status = 'Paid';
                if($model->save()){
                    $license = new \app\models\Licenses();
                    $license->user_id = $application->user_id;
                    $license->application_id = $id;
                    $license->start_date = date('Y-m-d');
                    $license->end_date = date('2022-m-d');
                    $license->save();
                    $application->status = 'Complete';
                    $application->save();
                    Yii::$app->session->setFlash('success','Please Go ahead and download license!');
                    return $this->redirect(['/member/licenses/index']);
                }else{
                    print_r($model->getFirstErrors());
                }
            } catch (IntegrityException $e) {
                echo $e->getMessage();
            } catch (NotFoundHttpException $e) {
                echo $e->getMessage();
            }
            return $this->redirect(['/member/payments/index']);
        }

    }

    /**
     * Updates an existing Payments model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Payments model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Payments model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Payments the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Payments::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/member/views/applications/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */
/* @var $form yii\widgets\ActiveForm */
$types = \app\models\MembershipTypes::find()->all();
?>

<div class="applications-form">

    <?php $form = ActiveForm::begin(); ?>
    <?php $form->errorSummary($user); ?>

    <?= $form->field($model, 'user_id')->hiddenInput(['value'=>$user->id])->label(false) ?>

    <?= $form->field($model, 'status')->hiddenInput(['value'=>'Review'])->label(false) ?>

    <?= $form->field($model, 'category')->hiddenInput(['value'=>'Membership'])->label(false) ?>

    <?= $form->field($user, 'membership_type_id')->dropDownList(ArrayHelper::map($types, 'id','name')) ?>

<div class="row">
        <div class="col-md-3">
            <?= $form->field($user, 'alternative_email')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'occupation')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'organisation')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'organisation_size')->textInput(['type' => 'number']) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <?= $form->field($user, 'alternative_phone_number')->textInput(['type' => 'number']) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'other_phone_number')->textInput(['type' => 'number']) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'physical_address')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'city_of_residence')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <?= $form->field($user, 'country_of_residence')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'facebook_handle')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'twitter_handle')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($user, 'city_of_residence')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($user, 'brief_bio')->textarea(['rows' => 6]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($user, 'about_ictau')->textarea(['rows' => 6]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($user, 'other_comments')->textarea(['rows' => 6]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($user, 'reference')->textarea(['rows' => 6]) ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/member/views/applications/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = 'Create Applications';
$this->params['breadcrumbs'][] = ['label' => 'Applications', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="applications-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'user' => $user,            
    ]) ?>

</div>

modules/member/views/applications/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Applications';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="applications-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Apply For Membership', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id:text:Application Number ',
            'category',
            'user.membership.name:text:Membership Type',
            'user.membership.fee:text:Membership Fee',
            'status',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}'
            ],
        ],
    ]); ?>


</div>

modules/member/views/applications/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = 'Update Applications: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Applications', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="applications-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'user' => $user,            
    ]) ?>

</div>

modules/member/views/applications/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = $model->user->name;
$this->params['breadcrumbs'][] = ['label' => 'Applications', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="applications-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <p> 
    <?php if($model->status == 'Review'): ?>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Submit Application', ['submit-application', 'id' => $model->id], [
            'class' => 'btn btn-success',
            'data' => [
                'confirm' => 'Are you sure you want to submit this application?',
            ],
        ]) ?>
    <?php endif; ?>
    <?php if($model->status == 'Pending Payment'): ?>
        <!--?= Html::a('Bank Payment', ['payments/create', 'id' => $model->id], [
            'class' => 'btn btn-success',
            'data' => [
                'confirm' => 'Are you sure you want to make payment for this application?',
            ],
        ]) ?-->
        <?= Html::a('Make Payment', ['payments/olycash', 'id' => $model->id], [
            'class' => 'btn btn-primary',
            'data' => [
                'confirm' => 'Are you sure you want to make payment for this application?',
            ],
        ]) ?>
    <?php endif; ?>

    </p>


    <div class="row">
        <div class="col-md-6">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id:text:Application Number ',
                    'category',
                    'user.membership.name:text:Membership Type',
                    'user.membership.fee:text:Membership Fee',
                    'status',
                ],
            ]) ?>
        </div>
        <div class="col-md-6">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'user.email',
                    'user.primary_phone_number',
                    'user.occupation',
                    'user.physical_address',
                    'user.city_of_residence',
                ],
            ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'user.alternative_email',
                    'user.organisation',
                    'user.organisation_size',
                    'user.physical_address',
                    'user.alternative_phone_number',
                ],
            ]) ?>
        </div>
        <div class="col-md-6">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'user.country_of_residence',
                    'user.facebook_handle',
                    'user.twitter_handle',
                    'user.physical_address',
                    'user.other_phone_number',
                ],
            ]) ?>
        </div>
    </div>


</div>