modules/member/controllers/PaymentsController.php
<?php

namespace app\modules\member\controllers;

use Yii;
use app\models\Payments;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PaymentsController implements the CRUD actions for Payments model.
 */
class PaymentsController extends Controller
{

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Payments models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Payments::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Payments model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Payments model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Payments();
        $application = \app\models\Applications::findOne($id);

        $alreadyPaid = Payments::find()
        ->where(['application_id'=>$id])->limit(1)->one();
        if($alreadyPaid){
            Yii::$app->session->setFlash('error','You already made a payment that is pending approval!');
            return $this->redirect(['applications/view','id'=>$id]);
        }

        if ($model->load(Yii::$app->request->post()) ) {
            $model->receipt = UploadedFile::getInstance($model, 'receipt');
            if($model->receipt){
                $photoPath = time().$model->receipt->baseName . '.' . $model->receipt->extension;
                $model->file = $photoPath;
                $model->user_id = \Yii::$app->user->id;
                $model->application_id = $id;
                $model->receipt->saveAs(Yii::getAlias('@webroot') .'/receipts/' . $photoPath);
                if($model->save()){
                    $application->status = $model->status;
                    $application->save(false);
                    Yii::$app->session->setFlash('success','Payment submitted successfully and is pending approval!');
                    return $this->redirect(['applications/view','id'=>$id]);        
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
            'application' => $application,
        ]);
    }

    public function actionOlycash($id)
    {
        $application = \app\models\Applications::findOne($id);

        
        $alreadyPaid = Payments::find()
        ->where(['application_id'=>$id])->limit(1)->one();
        if($alreadyPaid){
            Yii::$app->session->setFlash('error','You already made a payment that is pending approval!');
            return $this->redirect(['applications/view','id'=>$id]);
        }

        return $this->render('olycash', [
            'application' => $application,
        ]);
    }

    public function actionConfirm($id){
        // Yii::$app->controller->enableCsrfValidation = false;
        $application = \app\models\Applications::findOne($id);
        
        $purchase_id = $_POST['purchase_id'];
        $message = $_POST['message'];
        $payment_type = $_POST['payment_type'];
        if($message == 'success'){
            try {
                $model = new Payments();
                $model->user_id = \Yii::$app->user->id;
                $model->application_id = $id;
                $model->reference_number = $purchase_id;
                $model->payment_type ='Olycash';
                $model->amount = $application->user->membership->fee;
                $model->name =$application->user->name;
                $model->phone_number = $application->user->primary_phone_number;
                $model->status = 'Paid';
                if($model->save()){
                    $license = new \app\models\Licenses();
                    $license->user_id = $application->user_id;
                    $license->application_id = $id;
                    $license->start_date = date('Y-m-d');
                    $license->end_date = date('2022-m-d');
                    $license->save();
                    $application->status = 'Complete';
                    $application->save();
                    Yii::$app->session->setFlash('success','Please Go ahead and download license!');
                    return $this->redirect(['/member/licenses/index']);
                }else{
                    print_r($model->getFirstErrors());
                }
            } catch (IntegrityException $e) {
                echo $e->getMessage();
            } catch (NotFoundHttpException $e) {
                echo $e->getMessage();
            }
            return $this->redirect(['/member/payments/index']);
        }

    }

    /**
     * Updates an existing Payments model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Payments model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Payments model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Payments the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Payments::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/member/views/payments/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Payments */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="payments-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'payment_type')->textInput(['value' => 'Bank', 'readonly'=>true]) ?>

    <?= $form->field($model, 'amount')->textInput(['value'=>$application->user->membership->fee]) ?>

    <?= $form->field($model, 'status')->hiddenInput(['value' => 'Paid'])->label(false) ?>

    <?= $form->field($model, 'receipt')->fileInput(['required'=>true]); ?>

    <?= $form->field($model, 'name')->hiddenInput(['value'=>$application->user->name])->label(false) ?>

    <?= $form->field($model, 'phone_number')->hiddenInput(['value'=>$application->user->primary_phone_number])->label(false) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/member/views/payments/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Payments */

$this->title = 'Make Payment';
$this->params['breadcrumbs'][] = ['label' => 'Payments', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="payments-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'application' => $application,
        ]) ?>

</div>

modules/member/views/payments/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Payments';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="payments-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Payments', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'user_id',
            'payment_type',
            'application_id',
            'amount',
            //'status',
            //'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',
            //'name',
            //'phone_number',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

modules/member/views/payments/olycash.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Payments */

$this->title = 'Oly Cash';
$this->params['breadcrumbs'][] = ['label' => 'Payments', 'url' => ['payments/olycash','id'=>$application->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="payments-create panel">
    <div class="panel-heading">
        <h1 class="panel-title">Pay With OlyCash</h1>
    </div>
    <div class="panel-body">
        <script>(function(d, s, id) {var js, ojs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "https://share.olycash.com/en-us/sdk.js";ojs.parentNode.insertBefore(js, ojs);}(document, 'script', 'olycash-js-sdk'));</script>
        <!-- OPTIONAL: You can remove and incorporate this table in your form if desired -->
        <table class="amount-entry-form" style="border-collapse: collapse !important; max-width:250px !important;"><tr>
                <td style="border:0px;font-weight:bold;font-family: Arial, sans-serif; font-size: 17px;">Amount: </td>
                <td style="border:0px;"><select id="olycash__tempcurrency_1543470912" name="olycash__tempcurrency_1543470912" class="__olycash-temp-currency-field" style="width:85px;height:40px;padding:9px 5px 8px 5px;border: 1px solid #B2B2B2; background-color: #FFFFFF;font-family: Arial, sans-serif; font-size: 17px;"><option value="" disabled>Currency</option><option value="UGX" selected>UGX</option><option value="KES">KES</option><option value="TZS">TZS</option><option value="GHS">GHS</option><option value="ARS">ARS</option><option value="AUD">AUD</option><option value="BRL">BRL</option><option value="CAD">CAD</option><option value="CHF">CHF</option><option value="CZK">CZK</option><option value="DKK">DKK</option><option value="EUR">EUR</option><option value="GBP">GBP</option><option value="HKD">HKD</option><option value="HUF">HUF</option><option value="ILS">ILS</option><option value="JPY">JPY</option><option value="MXN">MXN</option><option value="MYR">MYR</option><option value="NOK">NOK</option><option value="NZD">NZD</option><option value="PHP">PHP</option><option value="PLN">PLN</option><option value="RUB">RUB</option><option value="SEK">SEK</option><option value="SGD">SGD</option><option value="THB">THB</option><option value="TRY">TRY</option><option value="TWD">TWD</option><option value="USD">USD</option></select></td>
                <td style="border:0px;">
            <input type="text" id="olycash__temptotal_1543470912" name="olycash__temptotal_1543470912" style="width:100px;height:40px;padding:10px;border: 1px solid #B2B2B2; background-color: #FFFFFF;font-family: Arial, sans-serif; font-size: 17px;" class="__olycash-temp-amount-field" value="<?=$application->user->membership->fee;?>" readonly="readonly" placeholder="0.00" maxlength="12"></td></tr></table><!-- END OPTIONAL --><!-- Your share code -->
            
            <!-- For Dev Testing Please uncomment the line below -->
            <!-- <div class="olycash-pay debit-only olycash--window" style="width:100% !important;" data-id="133C9BD_8B35E"> -->
            <div class="olycash-pay olycash--window" style="width:100% !important;" data-ignorefrequency="Y" data-id="133C9C6_D83460"> 
            <input type="hidden" id="olycash__category" name="olycash__category" value="156"/>
            <input type="hidden" id="olycash__total" name="olycash__total" value="<?=$application->user->membership->fee;?>"/>
            <input type="hidden" id="olycash__currency" name="olycash__currency" value="UGX"/>
            <input type='hidden' id='olycash__post_process' name='olycash__post_process' value='olycashPostProcess'/>
            <input type='hidden' id='olycash__post_response' name='olycash__post_response' value='<?= \yii\helpers\Url::to(['payments/confirm','id'=>$application->id],true);?>'/>
            <input type='hidden' id='olycash__buyer_name' name='hidden' value="<?= $application->user->name ?>"/>
            <input type='hidden' id='olycash__third_party_fee_paid_by' name='olycash__third_party_fee_paid_by' value="payer"/>        
        </div> 
        </div>
    </div>

</div>


<script>



    function olycashPostProcess(data){
        console.log(data);
        notifyPaymentCompletion(data);
    }

    function notifyPaymentCompletion(data) {
         jQuery.post('<?= \yii\helpers\Url::to(['confirm','id'=>$application->id],true);?>', {'purchase_id': purchaseId, 'message': data.message, 'method': data.payment_type}, function(response){
             console.log('Achest API notified. Response from API: '+JSON.stringify(response));
         });
    }

</script>

modules/member/views/payments/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Payments */

$this->title = 'Update Payments: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Payments', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="payments-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/member/views/payments/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Payments */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Payments', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="payments-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'payment_type',
            'application_id',
            'amount',
            'status',
            'created_at',
            'updated_at',
            'created_by',
            'updated_by',
            'name',
            'phone_number',
        ],
    ]) ?>

</div>